import type { Scrap, Company, Booking } from "@/types";

export const mockCompanies: Company[] = [
  {
    id: "c1",
    owner_id: "u1",
    name: "GreenTech Recyclers",
    industry_type: "Electronics Manufacturing",
    address: "Plot 42, Industrial Area Phase II",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560058",
    latitude: 12.97,
    longitude: 77.59,
    logo_url: null,
    description:
      "Leading electronics manufacturer with 15+ years of experience. We generate high-quality e-waste and metal scrap from our production facilities.",
    created_at: "2025-12-01T10:00:00Z",
  },
  {
    id: "c2",
    owner_id: "u2",
    name: "Tata Steel Works",
    industry_type: "Steel Manufacturing",
    address: "Survey No. 88, MIDC Taloja",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "410208",
    latitude: 19.08,
    longitude: 73.1,
    logo_url: null,
    description:
      "One of India's premier steel manufacturing units. Regular scrap output from our rolling mill and fabrication divisions.",
    created_at: "2025-11-15T10:00:00Z",
  },
  {
    id: "c3",
    owner_id: "u3",
    name: "PackRight Industries",
    industry_type: "Packaging",
    address: "D-Block, Naraina Industrial Area",
    city: "Delhi",
    state: "Delhi",
    pincode: "110028",
    latitude: 28.63,
    longitude: 77.14,
    logo_url: null,
    description:
      "Premium packaging solutions provider. Our production generates clean, sorted cardboard and paper waste.",
    created_at: "2025-11-20T10:00:00Z",
  },
  {
    id: "c4",
    owner_id: "u4",
    name: "Sunrise Plastics Pvt Ltd",
    industry_type: "Plastic Manufacturing",
    address: "G-14, Guindy Industrial Estate",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600032",
    latitude: 13.01,
    longitude: 80.22,
    logo_url: null,
    description:
      "Manufacturer of industrial-grade plastic components. We produce recyclable HDPE and PP scrap material.",
    created_at: "2025-10-05T10:00:00Z",
  },
  {
    id: "c5",
    owner_id: "u5",
    name: "ClearView Glass Corp",
    industry_type: "Glass Manufacturing",
    address: "Plot 7, Sector 37",
    city: "Gurgaon",
    state: "Haryana",
    pincode: "122001",
    latitude: 28.46,
    longitude: 77.02,
    logo_url: null,
    description:
      "Architectural and automotive glass manufacturer with consistent output of high-purity glass cullet.",
    created_at: "2025-09-10T10:00:00Z",
  },
  {
    id: "c6",
    owner_id: "u6",
    name: "AutoParts Hub",
    industry_type: "Automotive",
    address: "Peenya Industrial Area, 2nd Stage",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560058",
    latitude: 13.03,
    longitude: 77.52,
    logo_url: null,
    description:
      "Automotive parts manufacturer specializing in engine components. We produce mixed metal scrap from machining operations.",
    created_at: "2025-08-22T10:00:00Z",
  },
];

export const mockScraps: (Scrap & { companies?: { name: string; logo_url: string | null } })[] = [
  {
    id: "s1",
    seller_id: "u2",
    company_id: "c2",
    title: "500kg HMS Steel Scrap — Grade A",
    category: "Metal",
    quantity: 500,
    unit: "kg",
    price: 32000,
    description:
      "High-quality HMS (Heavy Melting Steel) scrap from our rolling mill. Clean, sorted, free of non-ferrous contamination. Available for immediate pickup. Ideal for re-melting and steel production.",
    images: [],
    address: "Survey No. 88, MIDC Taloja",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "410208",
    latitude: 19.08,
    longitude: 73.1,
    status: "available",
    created_at: "2026-03-08T10:00:00Z",
    companies: { name: "Tata Steel Works", logo_url: null },
  },
  {
    id: "s2",
    seller_id: "u1",
    company_id: "c1",
    title: "200 units — Server Motherboards (E-waste)",
    category: "E-waste",
    quantity: 200,
    unit: "pieces",
    price: 45000,
    description:
      "Decommissioned server motherboards with precious metal content (gold fingers, palladium). Data wiped and certified. Perfect for precious metal recovery.",
    images: [],
    address: "Plot 42, Industrial Area Phase II",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560058",
    latitude: 12.97,
    longitude: 77.59,
    status: "available",
    created_at: "2026-03-07T14:30:00Z",
    companies: { name: "GreenTech Recyclers", logo_url: null },
  },
  {
    id: "s3",
    seller_id: "u4",
    company_id: "c4",
    title: "1 Ton HDPE Plastic Scrap — Clean",
    category: "Plastic",
    quantity: 1000,
    unit: "kg",
    price: 18500,
    description:
      "Clean, sorted HDPE plastic scrap from our injection molding lines. No contamination, consistent quality. Color: mixed (mostly white and blue).",
    images: [],
    address: "G-14, Guindy Industrial Estate",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600032",
    latitude: 13.01,
    longitude: 80.22,
    status: "available",
    created_at: "2026-03-06T09:15:00Z",
    companies: { name: "Sunrise Plastics Pvt Ltd", logo_url: null },
  },
  {
    id: "s4",
    seller_id: "u3",
    company_id: "c3",
    title: "3 Tons OCC Cardboard — Baled",
    category: "Paper",
    quantity: 3000,
    unit: "kg",
    price: 12000,
    description:
      "Old Corrugated Cardboard (OCC) baled and ready for transport. Clean, dry, no lamination. Regular monthly supply available.",
    images: [],
    address: "D-Block, Naraina Industrial Area",
    city: "Delhi",
    state: "Delhi",
    pincode: "110028",
    latitude: 28.63,
    longitude: 77.14,
    status: "available",
    created_at: "2026-03-05T16:45:00Z",
    companies: { name: "PackRight Industries", logo_url: null },
  },
  {
    id: "s5",
    seller_id: "u5",
    company_id: "c5",
    title: "800kg Clear Glass Cullet",
    category: "Glass",
    quantity: 800,
    unit: "kg",
    price: 8500,
    description:
      "High-purity clear glass cullet from our float glass production line. Sorted, no ceramic or stone contamination. Ready for re-melt.",
    images: [],
    address: "Plot 7, Sector 37",
    city: "Gurgaon",
    state: "Haryana",
    pincode: "122001",
    latitude: 28.46,
    longitude: 77.02,
    status: "available",
    created_at: "2026-03-04T11:20:00Z",
    companies: { name: "ClearView Glass Corp", logo_url: null },
  },
  {
    id: "s6",
    seller_id: "u6",
    company_id: "c6",
    title: "Mixed Scrap Lot — Automotive Parts",
    category: "Mixed Scrap",
    quantity: 750,
    unit: "kg",
    price: 22000,
    description:
      "Mixed scrap lot from automotive parts production. Contains: aluminium turnings, steel offcuts, copper wire snippets, rubber gasket waste. Partially sorted.",
    images: [],
    address: "Peenya Industrial Area, 2nd Stage",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560058",
    latitude: 13.03,
    longitude: 77.52,
    status: "available",
    created_at: "2026-03-03T08:00:00Z",
    companies: { name: "AutoParts Hub", logo_url: null },
  },
  {
    id: "s7",
    seller_id: "u2",
    company_id: "c2",
    title: "2 Tons Cast Iron Scrap",
    category: "Metal",
    quantity: 2000,
    unit: "kg",
    price: 54000,
    description:
      "Cast iron scrap from our foundry operations. Includes broken molds and runners. Consistent composition, low phosphorus content.",
    images: [],
    address: "Survey No. 88, MIDC Taloja",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "410208",
    latitude: 19.08,
    longitude: 73.1,
    status: "available",
    created_at: "2026-03-02T13:00:00Z",
    companies: { name: "Tata Steel Works", logo_url: null },
  },
  {
    id: "s8",
    seller_id: "u1",
    company_id: "c1",
    title: "50 CRT Monitors — Bulk E-waste",
    category: "E-waste",
    quantity: 50,
    unit: "pieces",
    price: 7500,
    description:
      "Decommissioned CRT monitors from office upgrade. Contains lead glass and copper yoke components. Suitable for certified e-waste recyclers only.",
    images: [],
    address: "Plot 42, Industrial Area Phase II",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560058",
    latitude: 12.97,
    longitude: 77.59,
    status: "booked",
    created_at: "2026-02-28T10:00:00Z",
    companies: { name: "GreenTech Recyclers", logo_url: null },
  },
  {
    id: "s9",
    seller_id: "u4",
    company_id: "c4",
    title: "600kg PP Polypropylene Regrind",
    category: "Plastic",
    quantity: 600,
    unit: "kg",
    price: 24000,
    description:
      "Polypropylene regrind from our extrusion line. Uniform granule size, natural color. MFI: 10-12 g/10min. Excellent for reprocessing.",
    images: [],
    address: "G-14, Guindy Industrial Estate",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600032",
    latitude: 13.01,
    longitude: 80.22,
    status: "available",
    created_at: "2026-02-25T14:00:00Z",
    companies: { name: "Sunrise Plastics Pvt Ltd", logo_url: null },
  },
];

export const mockBookings: (Booking & {
  scraps?: { title: string; category: string; price: number };
  users?: { name: string };
})[] = [
  {
    id: "b1",
    buyer_id: "u10",
    seller_id: "u1",
    scrap_id: "s8",
    status: "confirmed",
    scheduled_at: "2026-03-15T10:00:00Z",
    created_at: "2026-03-01T10:00:00Z",
    scraps: { title: "50 CRT Monitors — Bulk E-waste", category: "E-waste", price: 7500 },
    users: { name: "EcoRecycle Solutions" },
  },
  {
    id: "b2",
    buyer_id: "u10",
    seller_id: "u2",
    scrap_id: "s1",
    status: "collected",
    scheduled_at: null,
    created_at: "2026-02-20T10:00:00Z",
    scraps: { title: "500kg HMS Steel Scrap — Grade A", category: "Metal", price: 32000 },
    users: { name: "Tata Steel Works" },
  },
];

export function isMockMode(): boolean {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  return !url || url === "your-supabase-url-here";
}
